# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocktailApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocktailApp

  pod 'RIBs', :git=> 'https://github.com/uber/RIBs', :tag => '0.9.2'
  pod 'RxSwift', '~> 5.0'
  pod 'RxCocoa', '~> 5.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Moya/RxSwift'
  pod 'Kingfisher'
  pod 'Then'
  pod 'TagListView'

  target 'CocktailAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CocktailAppUITests' do
    # Pods for testing
  end

end
