# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocktailApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocktailApp

  pod 'RIBs'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'Moya/RxSwift'
  pod 'Kingfisher'
  pod 'Then'
  pod 'TagListView'

  target 'CocktailAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CocktailAppUITests' do
    # Pods for testing
  end

end
